<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>false</IsAotCompatible>
    <NoWarn>$(NoWarn);IDE0051;CA2012,xUnit1031;IDE0039;IDE0130</NoWarn>
    <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.Extensions.Configuration.Binder.SourceGeneration</InterceptorsNamespaces>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Castle.Core" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Serilog.Sinks.XUnit" />
    <PackageReference Include="System.Net.Http" />
    <PackageReference Include="System.Text.RegularExpressions" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Enrichers.Environment" />
    <PackageReference Include="Serilog.Expressions" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Sinks.Async" />
    <PackageReference Include="Serilog.Sinks.Debug" />
    <PackageReference Include="Serilog.Exceptions" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="AutoFixture" />
    <PackageReference Include="AutoFixture.AutoMoq" />
    <PackageReference Include="AutoFixture.SeedExtensions" />
    <PackageReference Include="AutoFixture.Xunit2" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net10.0' ">
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing.XUnit" />
    <ProjectReference Include="..\Arc4u.Dependency.Tool\Arc4u.Dependency.Tool.csproj" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all"/>
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" PrivateAssets="all"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Arc4u.AspNetCore.Results\Arc4u.AspNetCore.Results.csproj" />
    <ProjectReference Include="..\Arc4u.Authorization\Arc4u.Authorization.csproj" />
    <ProjectReference Include="..\Arc4u.Caching.Memory\Arc4u.Caching.Memory.csproj" />
    <ProjectReference Include="..\Arc4u.Caching.Redis\Arc4u.Caching.Redis.csproj" />
    <ProjectReference Include="..\Arc4u.Caching.Sql\Arc4u.Caching.Sql.csproj" />
    <ProjectReference Include="..\Arc4u.Configuration.Decryptor\Arc4u.Configuration.Decryptor.csproj" />
    <ProjectReference Include="..\Arc4u.Dependency\Arc4u.Dependency.csproj" />
    <ProjectReference Include="..\Arc4u.Diagnostics.Serilog\Arc4u.Diagnostics.Serilog.csproj" />
    <ProjectReference Include="..\Arc4u.EfCore\Arc4u.EfCore.csproj" />
    <ProjectReference Include="..\Arc4u.FluentValidation\Arc4u.FluentValidation.csproj" />
    <ProjectReference Include="..\Arc4u.gRPC\Arc4u.gRPC.csproj" />
    <ProjectReference Include="..\Arc4u.MongoDB\Arc4u.MongoDB.csproj" />
    <ProjectReference Include="..\Arc4u.OAuth2.AspNetCore.Authentication\Arc4u.OAuth2.AspNetCore.Authentication.csproj" />
    <ProjectReference Include="..\Arc4u.OAuth2.Blazor\Arc4u.OAuth2.Blazor.csproj" />
    <ProjectReference Include="..\Arc4u.OAuth2.Client.Authentication\Arc4u.OAuth2.Client.Authentication.csproj" />
    <ProjectReference Include="..\Arc4u.OAuth2\Arc4u.OAuth2.csproj" />
    <ProjectReference Include="..\Arc4u.Results\Arc4u.Results.csproj" />
    <ProjectReference Include="..\Arc4u.Serializer.JSon\Arc4u.Serializer.JSon.csproj" />
    <ProjectReference Include="..\Arc4u\Arc4u.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Configs\appsettings.RejectedTypes.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Basic.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Configs\cert.pem">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>

    <None Update="Configs\EmptyAssemblies.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>

    <None Update="Configs\key.pem">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>

    <None Update="Configs\TestParser.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>

    <None Update="Configs\TestScopedParser.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
