<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <PackageId>Arc4u.FluentValidation</PackageId>
    <AssemblyName>Arc4u.Validation</AssemblyName>
    <NoWarn>$(NoWarn);IDE0130</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Arc4u.Data\Arc4u.Data.csproj" />
    <ProjectReference Include="..\Arc4u.Results\Arc4u.Results.csproj" />
  </ItemGroup>
</Project>
