<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <PackageId>Arc4u.Data</PackageId>
    <NoWarn>$(NoWarn);IDE0130</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Annotations" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Arc4u.Results\Arc4u.Results.csproj" />
    <ProjectReference Include="..\Arc4u\Arc4u.csproj" />
  </ItemGroup>
</Project>
