<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <PackageId>Arc4u</PackageId>
    <NoWarn>$(NoWarn);IDE0130</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Properties\**" />
    <Compile Remove="Threading\**" />
    <EmbeddedResource Remove="Properties\**" />
    <EmbeddedResource Remove="Threading\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentResults" />
    <PackageReference Include="System.ComponentModel.Annotations" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Arc4u.Configuration\Arc4u.Configuration.csproj" />
    <ProjectReference Include="..\Arc4u.Core\Arc4u.Core.csproj" />
    <ProjectReference Include="..\Arc4u.Dependency\Arc4u.Dependency.csproj" />
    <ProjectReference Include="..\Arc4u.Diagnostics\Arc4u.Diagnostics.csproj" />
    <ProjectReference Include="..\Arc4u.Threading\Arc4u.Threading.csproj" />
  </ItemGroup>
</Project>
