<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <PackageId>Arc4u.OAuth2</PackageId>
    <NoWarn>$(NoWarn);IDE0130</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Arc4u.Caching\Arc4u.Caching.csproj" />
    <ProjectReference Include="..\Arc4u.Results\Arc4u.Results.csproj" />
    <ProjectReference Include="..\Arc4u\Arc4u.csproj" />
  </ItemGroup>
</Project>
