<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <PackageId>Arc4u.Diagnostics.Serilog</PackageId>
    <NoWarn>$(NoWarn);IDE0130</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Serilog"/>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Arc4u.Diagnostics\Arc4u.Diagnostics.csproj" />
  </ItemGroup>
</Project>
