<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <PackageId>Arc4u.MongoDB</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Arc4u.Dependency\Arc4u.Dependency.csproj" />
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

</Project>
