<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <PackageId>Arc4u.Diagnostics.Serilog.Sinks.RealmDb</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Realm" />
    <PackageReference Include="Serilog.Sinks.PeriodicBatching" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Arc4u.Diagnostics.Serilog\Arc4u.Diagnostics.Serilog.csproj" />
    <ProjectReference Include="..\Arc4u.Diagnostics\Arc4u.Diagnostics.csproj" />
    <ProjectReference Include="..\Arc4u\Arc4u.csproj" />
  </ItemGroup>
</Project>
