<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <PackageId>Arc4u.Serializer.JSon</PackageId>
    <NoWarn>$(NoWarn);IDE0130</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" />
    <PackageReference Include="System.IO.Compression" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Arc4u.Diagnostics\Arc4u.Diagnostics.csproj" />
    <ProjectReference Include="..\Arc4u.Serializer\Arc4u.Serializer.csproj" />
  </ItemGroup>
</Project>
