<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <PackageId>Arc4u.OAuth2.Blazor</PackageId>
    <RootNamespace>Arc4u.Blazor</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="System.Formats.Asn1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Arc4u.OAuth2.Client\Arc4u.OAuth2.Client.csproj" />
  </ItemGroup>
  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>
</Project>
