<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <PackageId>Arc4u.Caching</PackageId>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);IDE0130</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Arc4u.Dependency\Arc4u.Dependency.csproj" />
    <ProjectReference Include="..\Arc4u.Diagnostics\Arc4u.Diagnostics.csproj" />
    <ProjectReference Include="..\Arc4u.Serializer\Arc4u.Serializer.csproj" />
  </ItemGroup>
</Project>
