<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <PackageId>Arc4u.Dependency</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Builder\**" />
    <EmbeddedResource Remove="Builder\**" />
    <None Remove="Builder\**" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' != 'netstandard2.0'">
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' != 'netstandard2.0'">
    <ProjectReference Include="..\Arc4u.Diagnostics\Arc4u.Diagnostics.csproj" />
    <ProjectReference Include="..\Arc4u.Threading\Arc4u.Threading.csproj" />
  </ItemGroup>
</Project>
