using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Arc4u.Standard")]
[assembly: InternalsVisibleTo("Arc4u.Standard.Dependency")]
[assembly: InternalsVisibleTo("Arc4u.Standard.Dependency.Composition")]
[assembly: InternalsVisibleTo("Arc4u.Standard.Caching")]
[assembly: InternalsVisibleTo("Arc4u.Standard.Caching.Memory")]
[assembly: InternalsVisibleTo("Arc4u.Standard.Caching.Redis")]
[assembly: InternalsVisibleTo("Arc4u.Standard.Caching.Sql")]
[assembly: InternalsVisibleTo("Arc4u.Standard.NServiceBus")]
[assembly: InternalsVisibleTo("Arc4u.Standard.Serializer")]
[assembly: InternalsVisibleTo("Arc4u.Standard.Serializer.JSon")]
[assembly: InternalsVisibleTo("Arc4u.Standard.Serializer.Protobuf")]
[assembly: InternalsVisibleTo("Arc4u.Standard.OAuth2")]
[assembly: InternalsVisibleTo("Arc4u.Standard.KubeMQ")]
[assembly: InternalsVisibleTo("Arc4u.Standard.OAuth2.Adal")]
[assembly: InternalsVisibleTo("Arc4u.Standard.OAuth2.Msal")]
[assembly: InternalsVisibleTo("Arc4u.Standard.OAuth2.Blazor")]
[assembly: InternalsVisibleTo("Arc4u.Standard.OAuth2.AspNetCore")]
[assembly: InternalsVisibleTo("Arc4u.Standard.OAuth2.AspNetCore.Msal")]
[assembly: InternalsVisibleTo("Arc4u.Standard.OAuth2.AspNetCore.Api")]
[assembly: InternalsVisibleTo("Arc4u.Standard.OAuth2.Client")]
[assembly: InternalsVisibleTo("Arc4u.Standard.EF")]
[assembly: InternalsVisibleTo("Arc4u.Standard.gRPC")]
[assembly: InternalsVisibleTo("Arc4u.Universal")]
[assembly: InternalsVisibleTo("Arc4u.Xamarin.iOS")]
[assembly: InternalsVisibleTo("Arc4u.Windows.Mvvm")]
[assembly: InternalsVisibleTo("Arc4u.Xamarin.Forms.Mvvm")]
[assembly: InternalsVisibleTo("Arc4u.Standard.KubeMQ.AspNetCore")]


[assembly: InternalsVisibleTo("Arc4u")]
[assembly: InternalsVisibleTo("Arc4u.OAuth2")]
[assembly: InternalsVisibleTo("Arc4u.OAuth2.Owin")]
[assembly: InternalsVisibleTo("Arc4u.NServiceBus")]
[assembly: InternalsVisibleTo("Arc4u.NServiceBus.RabbitMQ")]
[assembly: InternalsVisibleTo("Arc4u.WsFederation")]
[assembly: InternalsVisibleTo("Arc4u.ServiceModel")]

