name: Build and publish a package in release.

on: 
  workflow_dispatch:
    inputs:
      nugetVersion:
        description: 'nuget version number x.y.z'     
        required: false
        type: string
        default: '8.2.0'
      nugetPackageIdPrefix:
        description: 'NuGet PackageId prefix (include the period if necessary)'
        required: false
        type: string
        default: ''
      publish:
        description: 'true or false' 
        type: boolean
        required: true
        default: false
        
jobs:
  build:
    uses: ./.github/workflows/CoreBuild.yml
    with:
      nugetVersion: ${{ github.event.inputs.nugetVersion }}
      nugetPreviewName: ''
      nugetPackageIdPrefix: ${{ github.event.inputs.nugetPackageIdPrefix }}
      publish: ${{ github.event.inputs.publish }}
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
