name: Build and publish preview

permissions:
  id-token: write   # required for GitHub OIDC
 
on: 
  workflow_dispatch:
    inputs:
      nugetVersion:
        description: 'nuget version number x.y.z'     
        required: false
        type: string
        default: '9.0.0'
      nugetPreviewName:
        description: 'nuget preview ?'     
        required: true
        default: '-preview01'
      nugetPackageIdPrefix:
        description: 'NuGet PackageId prefix (include the period if necessary)'
        required: false
        type: string
        default: ''
      publish:
        description: 'true or false' 
        type: boolean
        required: true
        default: false
        
jobs:
  build:
    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job    
    uses: ./.github/workflows/CoreBuild.yml
    with:
      nugetVersion: ${{ github.event.inputs.nugetVersion }}
      nugetPreviewName: ${{ github.event.inputs.nugetPreviewName }}
      nugetPackageIdPrefix: ${{ github.event.inputs.nugetPackageIdPrefix }}
      publish: ${{ github.event.inputs.publish }}
    secrets:
      NUGET_USER: ${{ secrets.NUGET_USER }}