name: Build And Publish

on: 
  workflow_call:
    inputs:
      nugetVersion:
        description: 'nuget version number x.y.z.w'     
        required: false
        type: string
      nugetVersionSpecific:
        description: 'nuget version number z.w for specific packages'     
        required: false
        type: string
      nugetPreviewName:
        description: 'nuget preview ?'     
        required: false
        type: string
      nugetPackageIdPrefix:
        description: 'NuGet PackageId prefix (include the period if necessary)'
        required: false
        type: string
      publish:
        description: 'Publish to nuget.org?' 
        type: string
        required: true
    secrets:
       NUGET_API_KEY:
         required: true
        
env:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'  
  netStandardVersion: '${{ github.event.inputs.nugetVersion }}'
  netStandardVersionNuget: '${{ github.event.inputs.nugetVersion }}${{ github.event.inputs.nugetPreviewName }}'
  iOSVersion: '11.2.${{ github.event.inputs.nugetVersionSpecific }}'
  iOSVersionNuget: '11.2.${{ github.event.inputs.nugetVersionSpecific }}${{ github.event.inputs.nugetPreviewName }}'
  AndroidVersion: '9.0.${{ github.event.inputs.nugetVersionSpecific }}'
  AndroidVersionNuget: '9.0.${{ github.event.inputs.nugetVersionSpecific }}${{ github.event.inputs.nugetPreviewName }}'
  UwpVersion: '10.18362.${{ github.event.inputs.nugetVersionSpecific }}'
  UwpVersionNuget: '10.38362.${{ github.event.inputs.nugetVersionSpecific }}${{ github.event.inputs.nugetPreviewName }}'
  PrismVersion: '7.2.${{ github.event.inputs.nugetVersionSpecific }}'
  PrismVersionNuget: '7.2.${{ github.event.inputs.nugetVersionSpecific }}${{ github.event.inputs.nugetPreviewName }}'
  PublishToNuget: ${{ github.event.inputs.publish }}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
           dotnet-version: |
             6.0.x
             7.0.x
             8.0.100-preview.7.23376.3
      - name: Change Arc4u.Core versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.Core.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell
      - name: Change Arc4u.Standard versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.FluentValidation versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.FluentValidation.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.Configuration versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.Configuration.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.Configuration.Decryptor versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.Configuration.Decryptor.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.Dependency versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.Dependency.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.Dependency.ComponentModel versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.Dependency.ComponentModel.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.EfCore versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.EfCore.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.gRPC versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.gRPC.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.MongoDB versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.MongoDB.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.OData versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.OData.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.AspNetCore.gRpc versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.AspNetCore.gRpc.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.Caching versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.Caching.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.Caching.Memory versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.Caching.Memory.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.Caching.Sql versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.Caching.Sql.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.Caching.Redis versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.Caching.Redis.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.Caching.Dapr versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.Caching.Dapr.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.NServiceBus versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.NServiceBus.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.NServiceBus.Core versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.NServiceBus.Core.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.NServiceBus.RabbitMQ versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.NServiceBus.RabbitMQ.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.Authorization versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.Authorization.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell 
      - name: Change Arc4u.Standard.Dispatcher versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.Dispatcher.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell
      - name: Change Arc4u.Standard.Serializer versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.Results.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell   
      - name: Change Arc4u.Standard.Serializer versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.Serializer.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.Serializer.JSon versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.Serializer.JSon.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.Serializer.Protobuf versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.Serializer.Protobuf.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.Serializer.ProtobufV2 versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.Serializer.ProtobufV2.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.Data versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.Data.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.Threading versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.Threading.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.OAuth2.Client versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.OAuth2.Client.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.OAuth2 versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.OAuth2.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.OAuth2.Msal versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.OAuth2.Msal.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.OAuth2.AspNetCore.Authentication versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.OAuth2.AspNetCore.Authentication.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.OAuth2.AspNetCore versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.OAuth2.AspNetCore.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.OAuth2.AspNetCore.Api versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.OAuth2.AspNetCore.Api.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.OAuth2.AspNetCore.Adal versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.OAuth2.AspNetCore.Adal.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.OAuth2.AspNetCore.Blazor versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.OAuth2.AspNetCore.Blazor.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.OAuth2.Blazor versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.OAuth2.Blazor.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.Diagnostics versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.Diagnostics.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.Diagnostics.TraceListeners versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.Diagnostics.TraceListeners.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.Diagnostics.Serilog versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.Diagnostics.Serilog.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Standard.Diagnostics.Serilog.Sinks.RealmDb versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Standard.Diagnostics.Serilog.Sinks.RealmDb.csproj" "1.0.0.0" "${{env.netStandardVersion}}" "0.0.0.0" "${{env.netStandardVersionNuget}}"
        shell: powershell        
      - name: Change Arc4u.Prism.DI.Wpf versions
        run: .\src\Builds\SetVersion.ps1 "..\" "Arc4u.Prism.DI.Wpf.csproj" "1.0.0.0" "${{env.PrismVersion}}" "0.0.0.0" "${{env.PrismVersionNuget}}"
        shell: powershell         

      - name: Set the NuGet PackageId in the project files
        run: .\src\Builds\SetNuGetPackageIdPrefix.ps1 ".." "${{ github.event.inputs.nugetPackageIdPrefix }}"
        shell: powershell         

      - name: setup nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: latest
      - name: msbuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '[17.3, 18.0)'
 
      - name: nuget restore
        run: nuget restore .\src\arc4u.sln
 
      - name: build
        run: msbuild .\src\arc4u.sln /p:configuration=${{env.buildConfiguration}}
 
      - name: Run Test projects matching *UnitTest.csproj with filter Category = CI
        run: |
            Get-ChildItem -Filter *.*UnitTest.csproj -Recurse | ForEach-Object { dotnet test $_.FullName --no-restore -c ${{ env.buildConfiguration }} --filter 'Category = CI' }
        shell: pwsh     
 
      - name: Copy the nuget packages to a folder to have only one published.
        run: |
            md .\packages 
            Get-ChildItem -Path .\ -Recurse -Filter *.nupkg |  ForEach-Object { Copy-Item -Path $_.FullName -Destination (".\packages\"+$_.Name) }
        shell: pwsh  
 
      - name: Save nuget packages
        if: ${{ env.PublishToNuget == 'false'  }}
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            ./packages
          retention-days: 1
        
      - name: Publish packages
        if: ${{ env.PublishToNuget == 'true'  }}
        run: dotnet nuget push ".\packages\*.nupkg" --skip-duplicate --no-symbols --api-key ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
