
on:
  workflow_dispatch:

jobs:
  depchecktest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: latest
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore ./src/Arc4u.sln
  
      - name: Build
        run: dotnet build ./src/Arc4u.sln -c Release --no-restore

      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'Arc4u'
          path: '.'
          format: 'HTML'    
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports