
on:
  workflow_dispatch:

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'Arc4u'
          path: '.'
          format: 'HTML'    
          args: >
            --failOnCVSS 7
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports